### PR TITLE
adi:AD4170:Add support for AD4170

### PR DESCRIPTION
**Pull request by jansunil**
Add MATLAB support for AD4170

## Pull Request Description

Please replace this with a detailed description and motivation of the changes. 
You can tick the checkboxes below with an 'x' between square brackets or just check them after publishing the PR. 
If this PR contains a breaking change, list dependent PRs and try to push all related PRs at the same time.

## PR Type
- [ ] Bug fix (change that fixes an issue)
- [x] New feature (change that adds new functionality)
- [ ] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [x] I have performed a self-review of the changes
- [x] I have commented my code, at least hard-to-understand parts
- [x] I have build all projects affected by the changes in this PR
- [x] I have tested in hardware affected projects, at the relevant boards
- [x] I have signed off all commits from this PR
- [x] I have updated the documentation by running /docs/source/reference_api/gen_sysobj_doc.m script locally, if applies.

### CODE REVIEW

**Comment by jansunil** [comment]
@ribdp  - Do these changes look good for a merge?

**Comment by ribdp** [comment]
So the documentation would need some updates - 
1. We need to add the device name here and then run that script 
2. Index.rst and ad4170_iio.rst would then get updated/generated, and would need to be added to the PR
3. The existing CI/gen_doc changes can be removed as they aren't relevant to the new documentation system

**Comment by jansunil** [comment]
@ribdp - I've made the changes with the documentation- does it look ok now?

**Comment by ribdp** [comment]
Just one final change from my end - the device needs to be mentioned here as well - https://github.com/analogdevicesinc/PrecisionToolbox/blob/main/docs/source/index.rst

LGTM otherwise

**Comment by jansunil** [comment]
Changelog: Added the AD4170 entry in the docs/source/index.rst

**Review by SaikiranGudla — APPROVED** [review]

**Review by ribdp — APPROVED** [review]

**Pull request merged**
